--
-- PostgreSQL database dump (corrigido para Flyway)
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- ⚠️ Removido: SET transaction_timeout (não suportado)
-- ⚠️ Removido: comandos \restrict e \unrestrict

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- ============================================================
-- Tabelas e constraints
-- ============================================================

CREATE TABLE public.atividades (
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);
ALTER TABLE public.atividades OWNER TO postgres;
ALTER TABLE public.atividades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.atividades_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.comprovantes (
    id bigint NOT NULL,
    solicitacao_id bigint NOT NULL,
    tamanho bigint NOT NULL,
    upload_at timestamp(6) without time zone NOT NULL,
    caminho character varying(255) NOT NULL,
    content_type character varying(255) NOT NULL,
    nome_original character varying(255) NOT NULL
);
ALTER TABLE public.comprovantes OWNER TO postgres;
ALTER TABLE public.comprovantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comprovantes_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.cursos (
    total_horas_complementares integer NOT NULL,
    id bigint NOT NULL,
    nome character varying(150) NOT NULL
);
ALTER TABLE public.cursos OWNER TO postgres;
ALTER TABLE public.cursos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cursos_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.discentes (
    horas_cumpridas integer NOT NULL,
    ingressao date NOT NULL,
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    matricula character varying(255) NOT NULL
);
ALTER TABLE public.discentes OWNER TO postgres;

CREATE TABLE public.instituicoes (
    id bigint NOT NULL,
    cnpj character varying(255) NOT NULL,
    endereco character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);
ALTER TABLE public.instituicoes OWNER TO postgres;
ALTER TABLE public.instituicoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instituicoes_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.responsaveis (
    instituicao_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    cargo character varying(255) NOT NULL,
    siape character varying(255) NOT NULL,
    CONSTRAINT responsaveis_cargo_check CHECK (
        cargo IN ('PROFESSOR','COORDENADOR','DIRETOR')
    )
);
ALTER TABLE public.responsaveis OWNER TO postgres;

CREATE TABLE public.solicitacoes (
    carga_horaria_aproveitada integer NOT NULL,
    carga_horaria_solicitada integer NOT NULL,
    data_fim date NOT NULL,
    data_inicio date NOT NULL,
    data_solicitacao date NOT NULL,
    id bigint NOT NULL,
    instituicao_id bigint NOT NULL,
    subtipo_id bigint NOT NULL,
    observacao_discente character varying(350),
    observacao_responsavel character varying(350),
    discente_matricula character varying(255) NOT NULL,
    participacao character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT solicitacoes_participacao_check CHECK (
        participacao IN ('ORGANIZADOR','OUVINTE','PALESTRANTE')
    ),
    CONSTRAINT solicitacoes_status_check CHECK (
        status IN ('PENDENTE','DEFERIDA','INDEFERIDA')
    )
);
ALTER TABLE public.solicitacoes OWNER TO postgres;
ALTER TABLE public.solicitacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitacoes_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.subtipos (
    horas_max integer NOT NULL,
    horas_min integer NOT NULL,
    atividade_id bigint NOT NULL,
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL
);
ALTER TABLE public.subtipos OWNER TO postgres;
ALTER TABLE public.subtipos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subtipos_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE public.usuarios (
    ativo boolean NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    perfil character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL,
    CONSTRAINT usuarios_perfil_check CHECK (
        perfil IN ('DISCENTE','COORDENADOR','RESPONSAVEL','ADMIN')
    )
);
ALTER TABLE public.usuarios OWNER TO postgres;
ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

-- ============================================================
-- Constraints e FKs
-- ============================================================

ALTER TABLE ONLY public.atividades ADD CONSTRAINT atividades_nome_key UNIQUE (nome);
ALTER TABLE ONLY public.atividades ADD CONSTRAINT atividades_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comprovantes ADD CONSTRAINT comprovantes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.comprovantes ADD CONSTRAINT comprovantes_solicitacao_id_key UNIQUE (solicitacao_id);

ALTER TABLE ONLY public.cursos ADD CONSTRAINT cursos_nome_key UNIQUE (nome);
ALTER TABLE ONLY public.cursos ADD CONSTRAINT cursos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discentes ADD CONSTRAINT discentes_pkey PRIMARY KEY (matricula);
ALTER TABLE ONLY public.discentes ADD CONSTRAINT discentes_usuario_id_key UNIQUE (usuario_id);

ALTER TABLE ONLY public.instituicoes ADD CONSTRAINT instituicoes_cnpj_key UNIQUE (cnpj);
ALTER TABLE ONLY public.instituicoes ADD CONSTRAINT instituicoes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.responsaveis ADD CONSTRAINT responsaveis_pkey PRIMARY KEY (siape);
ALTER TABLE ONLY public.responsaveis ADD CONSTRAINT responsaveis_usuario_id_key UNIQUE (usuario_id);

ALTER TABLE ONLY public.solicitacoes ADD CONSTRAINT solicitacoes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subtipos ADD CONSTRAINT subtipos_descricao_key UNIQUE (descricao);
ALTER TABLE ONLY public.subtipos ADD CONSTRAINT subtipos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usuarios ADD CONSTRAINT usuarios_email_key UNIQUE (email);
ALTER TABLE ONLY public.usuarios ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

-- Foreign keys
ALTER TABLE ONLY public.responsaveis ADD CONSTRAINT fk_responsaveis_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
ALTER TABLE ONLY public.subtipos ADD CONSTRAINT fk_subtipos_atividade FOREIGN KEY (atividade_id) REFERENCES public.atividades(id);
ALTER TABLE ONLY public.discentes ADD CONSTRAINT fk_discentes_curso FOREIGN KEY (curso_id) REFERENCES public.cursos(id);
ALTER TABLE ONLY public.discentes ADD CONSTRAINT fk_discentes_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);
ALTER TABLE ONLY public.responsaveis ADD CONSTRAINT fk_responsaveis_instituicao FOREIGN KEY (instituicao_id) REFERENCES public.instituicoes(id);
ALTER TABLE ONLY public.solicitacoes ADD CONSTRAINT fk_solicitacoes_instituicao FOREIGN KEY (instituicao_id) REFERENCES public.instituicoes(id);
ALTER TABLE ONLY public.comprovantes ADD CONSTRAINT fk_comprovantes_solicitacao FOREIGN KEY (solicitacao_id) REFERENCES public.solicitacoes(id);
ALTER TABLE ONLY public.solicitacoes ADD CONSTRAINT fk_solicitacoes_discente FOREIGN KEY (discente_matricula) REFERENCES public.discentes(matricula);
ALTER TABLE ONLY public.solicitacoes ADD CONSTRAINT fk_solicitacoes_subtipo FOREIGN KEY (subtipo_id) REFERENCES public.subtipos(id);

-- ============================================================
-- Fim do script
-- ============================================================
